config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'topics#index'
  resources :topics do
    member do
      post 'comment' => 'topics#comment'
    end
  end
  get '/upvote' => 'topics#up_vote'
  get '/downvote' => 'topics#down_vote'
  get '/more_comment' => 'topics#more_comment'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :topic , inverse_of: :comments
  has_many :votes , dependent: :destroy , inverse_of: :comment
  has_many :up_votes , -> {where up: true}, class_name: 'Vote'
  has_many :down_votes , -> {where up: false}, class_name: 'Vote'
  validates :content_less ,:email ,:topic , presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
                                    message: "Enter Valid Email" }
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :comments ,dependent: :destroy  ,inverse_of: :topic
  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable ,:registerable ,:database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
  has_many :votes ,inverse_of: :user
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :comment ,inverse_of: :votes
  belongs_to :user , inverse_of: :votes
  validates :comment ,:user  , presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :set_topic, only: [:show, :edit, :update, :destroy ,:comment]
  before_action :authenticate_user! , only: [:comment ,:up_vote ,:down_vote]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @comments = @topic.comments.select(:id ,:content_less ,:email).page(params[:page]).per(10) || []
    if @comments.present?
      @comments.reject { |e|  e.up_votes.count - e.down_votes.count  >= -10 }
    end
    respond_to do |format|
      format.html
      format.json {render json: @comments}
    end
  end

  # GET /topics/new
  def new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create

  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update

  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy

  end

  def comment
    if current_user.present?
      begin
        data=comment_params
        @comment = @topic.comments.new(
                                      {
                                          content_less: data['content'][0..400],
                                          content_more: data['content'][401..-1] || nil,
                                          email:data[:email]
                                      }
        )
        respond_to do |format|
          if @comment.save
            format.html { redirect_to @topic, notice: 'Comment was saved successfuly' }
            format.json { render :show, status: :created, location: @topic }
          else
            format.html { redirect_to @topic ,alert: 'Unable to save comment' }
            format.json { render json: @comment.errors, status: :unprocessable_entity }
          end
        end
      rescue StandardError=>e
        puts " Error occured: #{e} "
        render json: {msg:' exception occured'}
      end
    else
      redirect_to new_user_session_path, :notice => 'Please Login To Comment'
    end
  end

  def up_vote
    begin
      if current_user.present?
        vote = Vote.find_by(user_id:current_user.id ,comment_id:params[:id].to_i)
        if vote.present?
          if vote.up
            render json: { msg:'Already Upvoted'  }
            return
          else
            vote.up = true
            if vote.save
              render json: { do:1 , change:1 }
              return
            else
              render json: {msg:'error'}
              return
            end
          end
        else
          vote = Vote.new(
              {
                  up:true,
                  user_id:current_user.id,
                  comment_id:params[:id]
              }
          )
          if vote.save
            render json: { do:1 }
            return
          else
            render json: {msg:'error'}
            return
          end
        end
      else
        flash[:alert] = 'Login to vote'
        render json: {msg:'Login first' ,login:1}
        return
      end
    rescue StandardError=>e
      puts " Error occured: #{e} "
      render json: {msg:' exception occured'}
      return
    end

  end
  def down_vote
    begin
      if current_user.present?
        vote = Vote.find_by(user_id:current_user.id ,comment_id:params[:id].to_i)
        if vote.present?
          unless vote.up
            render json: { msg:'Already Downvoted'  }
            return
          else

            if vote.update(up:false)
              render json: { do:1 , change:1 }
              return
            else
              render json: {msg:'error'}
              return
            end
          end
        else
          vote = Vote.new(
              {
                  up:false,
                  user_id:current_user.id,
                  comment_id:params[:id]
              }
          )
          if vote.save
            render json: { do:1 }
            return
          else
            render json: {msg:'error'}
            return
          end
        end
      else
        flash[:alert] = 'Login to vote'
        render json: {msg:'Login first'}
        return
      end
    rescue StandardError=>e
      puts " Error occured: #{e} "
      render json: {msg:' exception occured'}
      return
    end

  end

  def more_comment
    begin
      comment = Comment.find(params[:id].to_i)
      more_content = comment.present? ? comment.content_more: '' || ''
      render json: { more:more_content }
    rescue StandardError=>e
      puts " Error occured: #{e} "
      render json: {msg:' exception occured'}
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name)
    end

    def comment_params
      params.require(:comment).permit(:content,:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum</title>
  <link href="https://unpkg.com/basscss@8.0.1/css/basscss.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header flex justify-start">
      <%= link_to 'Devise Demo', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav flex justify-center">
        <li><%= link_to 'Home', root_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu flex justify-end" role="menu">
                <li class="mr4"><%= link_to 'Profile', edit_user_registration_path %></li>
                <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to 'Log In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<p id="notice"><%= notice %></p>

<%= yield %>

</body>
</html>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field flex justify-center h4 mt3">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions flex justify-center mt3">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1 class="flex justify-center">Editing Topic</h1>

<%= render 'form' %>

<p class="flex justify-center h5 mt4"><%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>
</p>

app/views/topics/index.html.erb
<h1 class="flex justify-center">Listing Topics</h1>

<table>
  <thead>
    <tr>
      <th class="flex justify-start h3 mb3">Name</th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr class="flex-wrap content-start">
        <td class="col-8"><%= link_to topic.name ,topic_path(topic) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/topics/new.html.erb
<h1 class="flex justify-center">New Topic</h1>

<%= render 'form' %>

<p class="flex justify-center h3"><%= link_to 'Back', topics_path %></p>

app/views/topics/show.html.erb
<p class="flex justify-center h3">
  <strong>Name:</strong>
  <%= @topic.name %>
</p>

<h1 class="flex justify-center">Listing Comments</h1>
<div class="scroll">
    <table class="mb3">
      <thead>
      <tr class="flex-container">
        <th class="flex-item">Content</th>
        <th class="flex-item">Email</th>
        <th class="flex-item">Up Vote</th>
        <th class="flex-item">Down Vote</th>
      </tr>
      </thead>
          <tbody>
          <% @comments.each do |comment| %>
              <tr class="flex-container">
                <td class="flex-item p1"><%= comment.content_less %><span class="more-content <%=comment.id%>"></span><span class="more <%=comment.id%>" style="font-size: 0.8rem;font-weight: 600;padding-left: 10px;">More</span></td>
                <td class="flex-item p1"><%= comment.email %></td>
                <td class="flex-item p1"><span class="up-count <%=comment.id%>" ><%= comment.up_votes.count %></span><span class="up <%=comment.id%> ml1" ><%= image_tag "like.png", :style => "width:2rem;height:2rem" %></span></td>
                <td class="flex-item p1"><span class="down-count <%=comment.id%>"><%= comment.down_votes.count %></span><span class="down <%=comment.id%> ml1"><%= image_tag "down.png",:style => "width:2rem;height:2rem" %></span></td>
              </tr>

          <% end %>
          </tbody>
    </table>
</div>


<%= form_tag  comment_topic_path , :method => 'post' do |f| %>
    <% if @comment.present? && @comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
            <% @comment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field flex justify-center">
      <%= label_tag :content %><br>
      <%= text_area_tag 'comment[content]' ,nil,required:true %>
    </div>
    <div class="field flex justify-center">
      <%= label_tag :email %><br>
      <%= text_field_tag 'comment[email]',nil,required:true %>
    </div>
    <div class="actions flex justify-center">
      <%= submit_tag 'Comment' %>
    </div>
<% end %>
<p class="flex justify-center h3"> <%= link_to '< Back', topics_path %> </p>
<script type="text/javascript" charset="utf-8">

    $(document.body).on('click',".more",function(){
        id = this.classList[1]
        self = this
        $.ajax({
            url: "/more_comment?id="+id,
            success: function(response) {
                if(response.more != null)
                    $('.more-content.'+id).text(response.more)
                $('.more.'+id).css("display","none")

            },
            error:function(){

            }
        })
    })
    $(document.body).on('click',".up",function(){
        id = this.classList[1]
        self = this
        $.ajax({
            url: "/upvote?id="+id,
            success: function(response) {
                if(response.do == '1')
                    $('.up-count.'+id).text(parseInt($('.up-count.'+id).text())+1)
                if(response.change == '1')
                    $('.down-count.'+id).text(parseInt($('.down-count.'+id).text())-1)
                if(response.login == '1')
                    alert('Please Login To Vote')

            },
            error:function(){

            }
        })
    })

    $(document.body).on('click',".down" ,function(){
        id = this.classList[1]
        self = this
        $.ajax({
            url: "/downvote?id="+id,
            success: function(response) {
                if(response.do == '1')
                    $('.down-count.'+id).text(parseInt($('.down-count.'+id).text())+1)
                if(response.change == '1')
                    $('.up-count.'+id).text(parseInt($('.up-count.'+id).text())-1)
                if(response.login == '1')
                    alert('Please Login To Vote')
            },
            error:function(){

            }
        })
    })
    $(window).height($(window).height()+100)
    page = 2
    up_vote_img = "<img style='width:2rem;height:2rem' src='/assets/like-36d598aee302378b03843cd9b66867539cb9d83b036d6752632eb2bc151efa4f.png' alt='Up Vote' />"
    down_vote_img ="<img style='width:2rem;height:2rem' src='/assets/down-f2f3c2153f1ad3cadeb92760c48f9925743bc326eea0bee389fdd5a16870ef7d.png' alt='Down Vote' />"
    if($('.scroll').height() > $('table').height()){
        $('table').height($('.scroll').height()+20)
    }

    var myScroll = new IScroll('.scroll',{
        mouseWheel: true});
    myScroll.on( 'scrollEnd', function(){
        if ((Math.abs(this.y) > $('table').height() - $('.scroll').height() -10) ){
            self = this
            $.ajax({
                url: "/topics/" + <%= @topic.id %>+ ".json?page="+page,
                success: function(response) {
                    for(i = 0 ; i< response.length ;i++) {
                        con = "<tr class='flex-container'> <td class='flex-item p1'>"+response[i].content_less+"<span class='more-content "+response[i].id+"'></span><span class='more "+response[i].id+"' style='font-size: 0.8rem;font-weight: 600;padding-left: 10px;'>More</span></td> <td class='flex-item p1'>"+response[i].email+"</td> <td class='flex-item p1'><span class='up-count "+response[i].id+"' >" +response[i].up_votes+"</span><span class='up " +response[i].id+" ml1' >" +up_vote_img +"</span></td> <td class='flex-item p1'><span class='down-count " +response[i].id+"'>"+response[i].down_votes+"</span><span class='down "+response[i].id+" ml1'>"+ down_vote_img+"</span></td></tr>"
                        $('tbody').append(con)
                    }
                    if(response.con == true) {
                        page++
                        self.refresh()
                    }

                },
                error:function(){

                }
            })
        }
    })

</script>